name: Generate ASCII Artwork

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v6

            - name: install Cowsay Program
              run: sudo apt-get install cowsay -y

            - name: Execute Cowsay CMD for the Dragon
              run: cowsay -f dragon "Run for cover, I am a DRAGON.....RAWR" >> dragon.txt

            - name: Execute Cowsay CMD for the Lion
              run: cowsay -f lion "Run for cover, I am a LION.....RAWR" >> lion.txt

            - name: Test File Exists
              run: |
                grep -i "dragon" dragon.txt
                grep -i "lion" lion.txt

            - name: Read File
              run: |
                cat dragon.txt
                cat lion.txt

            - name: List repo Files
              run: ls -ltra